Troubleshooting github check error
When mockClient is imported it causes errors
 1) Cannot find name 'ReadableStream'. -> add 'dom' to tsconfig
 2) on github checks fails with
   Error: node_modules/aws-sdk-client-mock/dist/types/libStorage.d.ts(8,95): error TS2307:
   Cannot find module '@aws-sdk/client-s3' or its corresponding type declarations.

When removing the mockClient import and skipping tests under
"Successful provisioning operations", the checks pass.

Testing to see if adding @aws-sdk/client-s3 as dev helps.
- appears to have worked after installing this, but not sure
- removing to try and see if the error comes back
- error does return, so adding @aws-sdk/client-s3 back as dep

Ticket: AT-7050