Wrap each FOR tag in IF conditional to prevent failure
Previously when collections objects are null
FOR loops would fail with error:
InvalidCommandError: Invaid FOR command
(can only iterate over Array)

Systematically tested all variations

Ticket: AT-8610